import type { Metadata } from "next";
import Link from "next/link";
import Header from "@/app/components/Header/Header";
import Footer from "@/app/components/Footer/Footer";
import './globals.css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt">
      <body>
        <Header />
        {/* Adicionado menu de navegação */}
        <nav className="flex justify-center space-x-8 mb-8">
  <Link href="/" className="text-lg font-medium hover:text-gray-400 transition">
    Home
  </Link>
  <Link href="/produtos" className="text-lg font-medium hover:text-gray-400 transition">
    Produtos
  </Link>
  <Link href="/tecnologias" className="text-lg font-medium hover:text-gray-400 transition">
    Tecnologias
  </Link>
</nav>
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
