import type { Metadata } from "next";
import localFont from "next/font/local";
import Header from '@/app/components/Header/Header';
import Footer from '@/app/components/Footer/Footer';
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt">
      <body>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
